### PR TITLE
Making this work with Forestry 3.6.

### PR DESCRIPTION
**Pull request by airbreather**
As prophecy has foretold in #2.

### CODE REVIEW

**Comment by Vexatos** [comment]
Closes #2.

**Comment by Vexatos** [comment]
Will "release" a build of this soon.

**Comment by Vexatos** [comment]
There you go: http://files.vex.tty.sh/BeeSpecific/.

**Comment by airbreather** [comment]
Cool, thanks!  One thing to point out, you should probably distinguish in the filenames which version of Forestry the jar is made for.

**Comment by Vexatos** [comment]
I am... Am I not?

**Comment by airbreather** [comment]
At the time I wrote that, it wasn't like that.  It's like that now.

**Pull request merged**
